"""Write an ExplanationReport as both Markdown (human) and JSON (machine).

The two files live side-by-side so:
    - operators read the .md
    - Phase 11 LLM ops co-pilot's RAG retrieval consumes the .json (stable schema)
    - downstream MLOps tools can validate report shape with one schema file
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

from .report_schema import ExplanationReport


def write_report(report: ExplanationReport, out_dir: Path) -> tuple[Path, Path]:
    """Write ``explanation_<window_idx>.md`` + ``.json`` to ``out_dir``.

    Returns ``(md_path, json_path)``.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / f"explanation_{report.window_idx:06d}.md"
    json_path = out_dir / f"explanation_{report.window_idx:06d}.json"

    # Pin UTF-8 — default on Windows is cp1252 which can't encode unicode glyphs.
    md_path.write_text(_render_markdown(report), encoding="utf-8")
    json_path.write_text(
        json.dumps(report.to_dict(), indent=2, default=str),
        encoding="utf-8",
    )
    return md_path, json_path


def _render_markdown(r: ExplanationReport) -> str:
    threshold_str = (
        f"{r.threshold:.4f}" if r.threshold is not None else "(not calibrated)"
    )
    fault_line = (
        f"\n**Predicted fault type:** `{r.fault_type_predicted}`\n"
        if r.fault_type_predicted else ""
    )
    physics_line = (
        f"\n**Physics model:** `{r.physics_model_name}`\n"
        if r.physics_model_name else ""
    )

    # Top-K channels table
    ch_lines = ["| rank | channel | normalized attribution | physics-covered |",
                "|---:|---|---:|:---:|"]
    for ch in r.ranked_channels[:15]:
        ch_lines.append(
            f"| {ch.rank} | `{ch.channel_name}` | {ch.score:.3f} | {'✓' if ch.physics_covered else ''} |"
        )
    ch_table = "\n".join(ch_lines)

    # Cascade
    if r.cascade:
        cas_lines = ["| source channel | weight | lag (steps) | via |",
                     "|---|---:|---:|---|"]
        for c in r.cascade:
            cas_lines.append(
                f"| `{c.source_channel}` | {c.weight:+.3f} | {c.lag_steps} | "
                f"{c.via or 'direct'} |"
            )
        cas_table = "\n".join(cas_lines)
    else:
        cas_table = "_No upstream causes found (coupling graph empty or no significant edges)._"

    plot_section = ""
    if r.plot_paths:
        plot_section = "\n## Plots\n\n" + "\n".join(
            f"- [{name}]({path})" for name, path in r.plot_paths.items()
        ) + "\n"

    notes_section = f"\n## Notes\n\n{r.notes}\n" if r.notes else ""

    return f"""# Anomaly explanation — window {r.window_idx}

**Detector:** `{r.detector_name}`
**Dataset:** `{r.dataset_name}`
**Window:** steps `[{r.window_idx}, {r.window_idx + r.window_length})`, starting at epoch ms `{r.window_start_ms}`
**Anomaly score:** `{r.anomaly_score:.4f}` (threshold: {threshold_str})
{fault_line}{physics_line}
**Attribution method:** `{r.attribution_method}`
**Coupling source:** `{r.coupling_source}`
**Generated:** {datetime.now(UTC).isoformat()}

## Top contributing channels

{ch_table}

## Upstream root-cause cascade

{cas_table}
{plot_section}{notes_section}
---
*Generated by dgx-ts explain (Phase 7).*
"""
